<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account' => '',
    'Account Mail Sent' => '',
    'Active' => '',
    'Alter Date' => '',
    'Amount' => '',
    'Are you sure you want to delete this item?' => '',
    'Average Wage Rate' => '',
    'Backend Password' => '',
    'Backend User Created' => '',
    'Bank Account Created' => '',
    'Bank Password' => '',
    'Bank Transaction ID' => '',
    'Business ID' => 'Y-tunnus',
    'City' => 'Kaupunki',
    'Clear field' => '',
    'Communication' => '',
    'Companies' => '',
    'Company ID' => '',
    'Costbenefit Calculation ID' => '',
    'Costbenefit Item Type ID' => '',
    'Create' => '',
    'Create Date' => '',
    'Create Demo Data' => '',
    'Create Init Data' => '',
    'Create Purchasing Orders' => '',
    'Create Time' => '',
    'Create {modelClass}' => '',
    'Created' => 'Luotu',
    'Delete' => 'Poista',
    'Description' => 'Kuvaus',
    'Email' => 'Sähköposti',
    'Employees' => 'Työntekijöitä',
    'Event Date' => '',
    'Event Time' => '',
    'Executed' => '',
    'Expiration Date' => '',
    'Futurality Business Register' => 'Futuralityn Yritystietojärjestelmä',
    'Hello, {username}!' => '',
    'ID' => '',
    'Industries' => 'Toimialat',
	'Industry' => 'Toimiala',
    'Industry ID' => '',
    'Lifetime' => '',
    'Maximum Wage Rate' => '',
    'Minimum Wage Rate' => '',
    'Name' => 'Nimi',
    'Nothing was found with business id \'{business_id}\'' => 'Y-tunnuksella \'{business_id}\' ei löytynyt yritystä',
    'Openerp Database Created' => '',
    'Openerp Password' => '',
    'Openerp Purchase Order ID' => '',
    'Order' => '',
    'Order Automation ID' => '',
    'Order Setup ID' => '',
    'Organization' => '',
    'Phone' => '',
    'Position' => '',
    'Postal Code' => '',
    'Reclaim Date' => '',
    'Rents' => '',
    'Reset' => '',
    'Rows' => '',
    'Search' => 'Hae',
    'Search a company by business ID' => 'Etsi yritystä y-tunnuksen perusteella',
    'Search results' => 'Haun tulokset',
    'Select date & time' => '',
    'Sent' => '',
    'Significance' => '',
    'Street' => '',
    'Tag' => '',
    'Token Customer ID' => '',
    'Token Key' => '',
    'Token Key ID' => '',
    'Token Setup ID' => '',
    'Turnover' => '',
    'Type' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Value' => '',
    'Week' => '',
    'Weight' => '',
    'Welcome!' => 'Tervetuloa!',
    'Year' => '',
	'computer-assembly' => 'Tietokoneiden kokoonpano',
	'computer-retail' => 'Tietokoneiden jälleenmyynti',
];
